# PodDisruptionBudget for Frontend

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: portfolio-prod
  labels:
    app: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
